In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

C:\Users\HP\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
data=pd.read_csv(r"C:\Users\HP\Downloads\acc_mode_data.csv")
data

State_UT  Year                  Mode  Total
0     A & N Islands  2001               Bicycle      0
1     A & N Islands  2001                   Bus      2
2     A & N Islands  2001                   Car      1
3     A & N Islands  2001                  Jeep      0
4     A & N Islands  2001  Other Motor Vehicles      2
...             ...   ...                   ...    ...
4905    West Bengal  2014                Others    369
4906    West Bengal  2014            Pedestrian    555
4907    West Bengal  2014         Three Wheeler    135
4908    West Bengal  2014           Truck/Lorry   1795
4909    West Bengal  2014           Two Wheeler   1254

[4910 rows x 4 columns]

In [3]:
data.iloc[736]

State_UT    Chandigarh
Year              2004
Mode        Pedestrian
Total               24
Name: 736, dtype: object

In [4]:
data.head()

State_UT  Year                  Mode  Total
0  A & N Islands  2001               Bicycle      0
1  A & N Islands  2001                   Bus      2
2  A & N Islands  2001                   Car      1
3  A & N Islands  2001                  Jeep      0
4  A & N Islands  2001  Other Motor Vehicles      2

In [5]:
data.tail()

State_UT  Year           Mode  Total
4905  West Bengal  2014         Others    369
4906  West Bengal  2014     Pedestrian    555
4907  West Bengal  2014  Three Wheeler    135
4908  West Bengal  2014    Truck/Lorry   1795
4909  West Bengal  2014    Two Wheeler   1254

In [6]:
data.isnull().sum()

State_UT    0
Year        0
Mode        0
Total       0
dtype: int64

In [7]:
ob1=LabelEncoder()
ob2=LabelEncoder()
ob3=LabelEncoder()

In [8]:
data["State_UT"]=ob1.fit_transform(data["State_UT"])
data["Mode"]=ob2.fit_transform(data["Mode"])

In [9]:
data

State_UT  Year  Mode  Total
0            0  2001     0      0
1            0  2001     1      2
2            0  2001     2      1
3            0  2001     3      0
4            0  2001     4      2
...        ...   ...   ...    ...
4905        36  2014     5    369
4906        36  2014     6    555
4907        36  2014     7    135
4908        36  2014     8   1795
4909        36  2014     9   1254

[4910 rows x 4 columns]

In [10]:
data["State_UT"].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36])

In [11]:
data["Mode"].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x=data.drop(["Total"],axis=1)
y=data.Total

In [13]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [14]:
xtrain

State_UT  Year  Mode
3024        22  2009     4
336          2  2006     6
2304        17  2007     4
2841        21  2005     1
3998        29  2008     8
...        ...   ...   ...
4426        33  2008     6
466          3  2005     6
3092        23  2002     2
3772        27  2014     2
860          6  2003     0

[3437 rows x 3 columns]

In [15]:
xtest

State_UT  Year  Mode
1718        13  2004     8
1412        11  2002     2
4208        31  2001     8
2589        19  2007     9
3352        24  2014     2
...        ...   ...   ...
1606        12  2007     6
3673        27  2004     3
1505        11  2011     5
1973        15  2002     3
736          5  2004     6

[1473 rows x 3 columns]

In [16]:
ytrain

3024       3
336        0
2304     741
2841     515
3998    1631
        ... 
4426      10
466       72
3092       9
3772      10
860       73
Name: Total, Length: 3437, dtype: int64

In [17]:
ytest

1718     918
1412       4
4208    3206
2589       0
3352      21
        ... 
1606     540
3673       4
1505       7
1973      24
736       24
Name: Total, Length: 1473, dtype: int64

### Linear Regression

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
model1=LinearRegression()

In [20]:
model1.fit(xtrain,ytrain)

LinearRegression()

In [21]:
print(model1.score(xtrain,ytrain)*100)
print(model1.score(xtest,ytest)*100)

7.345227487531936
6.701396672904569


### Decision Tree Regressor

In [22]:
from sklearn.tree import DecisionTreeRegressor

In [23]:
model2=DecisionTreeRegressor()

In [24]:
model2.fit(xtrain,ytrain)

DecisionTreeRegressor()

In [25]:
print(model2.score(xtrain,ytrain)*100)
print(model2.score(xtest,ytest)*100)

100.0
91.47061447015803


### Random Forest Regressor

In [26]:
from sklearn.ensemble import RandomForestRegressor

In [27]:
model3=RandomForestRegressor(n_estimators=100)

In [28]:
model3.fit(xtrain,ytrain)

RandomForestRegressor()

In [29]:
print(model3.score(xtrain,ytrain)*100)
print(model3.score(xtest,ytest)*100)

98.89718915281254
94.21245981187877


### KNNRegressor

In [30]:
from sklearn.neighbors import KNeighborsRegressor

In [31]:
model4=KNeighborsRegressor()

In [32]:
model4.fit(xtrain,ytrain)

KNeighborsRegressor()

In [33]:
print(model4.score(xtrain,ytrain)*100)
print(model4.score(xtest,ytest)*100)

66.98064753895041
48.43038930439939


### SVR

In [34]:
from sklearn.svm import SVR

In [35]:
model5=SVR()

In [36]:
model5.fit(xtrain,ytrain)

SVR()

In [37]:
print(model5.score(xtrain,ytrain)*100)
print(model5.score(xtest,ytest)*100)

-17.87024330097744
-19.386250895973678


### Adaboost Regressor

In [38]:
from sklearn.ensemble import AdaBoostRegressor

In [39]:
model6= AdaBoostRegressor(n_estimators=50)

In [40]:
model6.fit(xtrain,ytrain)

AdaBoostRegressor()

In [41]:
model6.score(xtrain,ytrain)*100

10.65443471163019

In [42]:
model6.score(xtest,ytest)*100

5.099428757942093

### Gradient Boost Reg

In [43]:
from sklearn.ensemble import GradientBoostingRegressor

In [44]:
model7 = GradientBoostingRegressor(n_estimators=100)

In [45]:
model7.fit(xtrain,ytrain)

GradientBoostingRegressor()

In [46]:
model7.score(xtrain,ytrain)*100

74.73467048112991

In [47]:
model7.score(xtest,ytest)*100

72.69882665142194

## Prediction

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4910 entries, 0 to 4909
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   State_UT  4910 non-null   int32
 1   Year      4910 non-null   int64
 2   Mode      4910 non-null   int32
 3   Total     4910 non-null   int64
dtypes: int32(2), int64(2)
memory usage: 115.2 KB


In [55]:
State_UT = input('enter the State/UT:')
State_UT = ob1.transform([State_UT])
State_UT

enter the State/UT:Chandigarh


array([5])

In [56]:
Year = int(input('Enter the Year :'))

Enter the Year :2009


In [57]:
Mode = input('Enter the Mode:')
Mode = ob2.transform([Mode])
Mode

Enter the Mode:Car


array([2])

In [58]:
result=model3.predict([[State_UT[0],Year,Mode[0]]])
prediction=int(np.round(result))
print(prediction)

4


C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
